### PR TITLE
Fix string deserialize exception

### LINKED ISSUE #73: Do not allow changing type of an existing key
Currently, we can override the type stored in a key. This can lead to exceptions during deserialisation.
However Redis doesn't allow this.

### PR DESCRIPTION
**Pull request by tuhuynh27**
Fixes #73 

For String byte[], it doesn't follow the java serialization protocol, thus a SerializationException will be thrown when deserializing on String byte[]

### CODE REVIEW

File: core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java [hunk 1]
```diff
@@ -115,7 +116,7 @@ public void init() {
                         } catch (Exception e) {
                             log.error(e.getMessage(), e);
                             if (e instanceof InvocationTargetException) {
-                                if (e.getCause() instanceof ClassCastException) {
+                                if (e.getCause() instanceof SerializationException || e.getCause() instanceof ClassCastException) {
```
Comment (the123saurav) [inline core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java:119]: Should we wrap the `SerializationException` thrown during deserilise to a custom one, so that we can distinguish it from the same thrown in call to serialise?

Comment (tuhuynh27) [reply core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java:119]: Like we need to merge SerializationException and ClassCastException to something like `KevaTypeException` right?

Comment (the123saurav) [reply core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java:119]: I meant we have code like this:
```
try {
            byte[] value = chronicleMap.get(key);
            LinkedList<BytesValue> list;
            list = value == null ? new LinkedList<>() : (LinkedList<BytesValue>) SerializationUtils.deserialize(value); <- can throw
            for (byte[] v : values) {
                list.addFirst(new BytesValue(v));
            }
            chronicleMap.put(key, SerializationUtils.serialize(list)); <- can throw
            return list.size();
        } finally {
            lock.unlock();
        }
```      
From 2 places same exception can be thrown but only 1 of them indicates client error.

Comment (the123saurav) [reply core/src/main/java/dev/keva/core/command/mapping/CommandMapper.java:119]: SOunds good!

**Review by the123saurav — APPROVED** [review]

**Comment by tuhuynh27** [comment]
Hi @the123saurav, created #75 backlog issue for your suggestion
